name: sample-puppeteer

on:
  pull_request:
    branches: [master, staging, production]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: "v14.17.0"
      - run: npm i
      - run: npm run build